CREATE TABLE escolas (
id INT PRIMARY KEY IDENTITY(1,1),
nome VARCHAR(100)
);

CREATE TABLE alunos(
id INT PRIMARY KEY IDENTITY(1,1),
nome VARCHAR(100),
cpf VARCHAR(14),
nota_1 DECIMAL(4,1),
nota_2 DECIMAL(4,1),
nota_3 DECIMAL(4,1)
);